## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 1.1
  - 1.2
  - nightly
addons:
    apt_packages:
        - gfortran  
notifications:
  email: false
git:
  depth: 99999999

after_script:  # TODO: change to after_success once https://github.com/JuliaLang/julia/issues/28306 is fixed
  # push coverage results to Codecov and Coveralls
  - julia -e 'using Pkg, OrdinalMultinomialModels; cd(joinpath(dirname(pathof(OrdinalMultinomialModels)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using OrdinalMultinomialModels; include(joinpath(dirname(pathof(OrdinalMultinomialModels)), "..", "docs", "make.jl"))'
      after_script: skip
      after_success: skip
      